#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged on staged files
pnpm exec lint-staged

# Note: Full typecheck disabled in pre-commit due to existing strict mode errors
# Run 'pnpm typecheck' manually before pushing
# TODO: Fix all TypeScript strict mode errors and re-enable typecheck in pre-commit
